"""Add shipping field to Order

Revision ID: 000d0e2ace5d
Revises: eb9bd5e12b3c
Create Date: 2025-01-20 23:19:40.525028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000d0e2ace5d'
down_revision = 'eb9bd5e12b3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('final_price', sa.Float(), nullable=False))
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=250),
               existing_nullable=False)
        batch_op.drop_column('shipping_cost')
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('shipping_cost', sa.FLOAT(), nullable=True))
        batch_op.alter_column('address',
               existing_type=sa.String(length=250),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('final_price')
        batch_op.drop_column('shipping')

    # ### end Alembic commands ###
